### PR TITLE
Update twitterHijack.sh

### PR DESCRIPTION
**Pull request by ZephrFish**

### CODE REVIEW

**Comment by paragonsec** [comment]
Lol saw this coming

**Comment by virtualdxs** [comment]
Damn you're fast!

**Review by tinkersec — APPROVED** [review]
Tested and approved.

**Review by Pompo17102 — COMMENTED** [review]
Here it's the bitcoin wallet address to make a payment for help bc1q5v34g2dym8c7x5mpfp7wdqp5hse38p99p4dggx

**Pull request merged**
